FROM maven:3.9.6-eclipse-temurin-21-alpine AS maven_dependencies
COPY pom.xml /tmp/
RUN mvn -B dependency:go-offline -f /tmp/pom.xml -s /usr/share/maven/ref/settings-docker.xml

FROM maven_dependencies as maven_build
COPY src /tmp/src/
COPY .git /tmp/.git/
COPY lombok.config /tmp/
WORKDIR /tmp/
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} library.jar
RUN java -Djarmode=layertools -jar library.jar extract

FROM eclipse-temurin:21.0.2_13-jdk-alpine
VOLUME /tmp
COPY --from=maven_build /tmp/dependencies/ ./
COPY --from=maven_build /tmp/snapshot-dependencies/ ./
COPY --from=maven_build /tmp/spring-boot-loader/ ./
COPY --from=maven_build /tmp/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]